// Static icon map — replaces the previous `import * as LucideIcons` pattern
// that pulled the entire lucide-react library (~180 KB) into the bundle.
// Adding a new DB icon now requires one line in both the import block and
// the map below (~30s of dev work per new category), but trims ~150 KB of
// First Load JS. Source list = `SELECT DISTINCT icon FROM
// glatko_service_categories WHERE is_p0 = TRUE`.
import {
  Anchor,
  Baby,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Building,
  Building2,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChefHat,
  CircuitBoard,
  ClipboardCheck,
  Cog,
  Compass,
  Crown,
  Disc,
  Droplets,
  Eye,
  GraduationCap,
  Grid3x3,
  Hammer,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  Home,
  KeyRound,
  Languages,
  Layers,
  MessageCircle,
  Monitor,
  Moon,
  Music,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pen,
  Plane,
  RotateCw,
  Ruler,
  Sailboat,
  Scissors,
  Settings,
  Shield,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Square,
  Star,
  Sun,
  Tag,
  Truck,
  UtensilsCrossed,
  Warehouse,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  Anchor,
  Baby,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Building,
  Building2,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChefHat,
  CircuitBoard,
  ClipboardCheck,
  Cog,
  Compass,
  Crown,
  Disc,
  Droplets,
  Eye,
  GraduationCap,
  Grid3x3,
  Hammer,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  Home,
  KeyRound,
  Languages,
  Layers,
  MessageCircle,
  Monitor,
  Moon,
  Music,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pen,
  Plane,
  RotateCw,
  Ruler,
  Sailboat,
  Scissors,
  Settings,
  Shield,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Square,
  Star,
  Sun,
  Tag,
  Truck,
  UtensilsCrossed,
  Warehouse,
  Wind,
  Wrench,
  Zap,
};

const FALLBACK: LucideIcon = Tag;

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) return FALLBACK;
  const Icon = ICON_MAP[name];
  if (Icon) return Icon;
  if (process.env.NODE_ENV !== "production") {
    console.warn(`[categoryIcon] Unknown lucide name: ${name}`);
  }
  return FALLBACK;
}
