-- ============================================================================
-- 017_glatko_search_synonyms_seed_batch1.sql
-- G-CAT-3: Sectoral synonym seed — BATCH 1 (7 remaining root categories)
--
-- Continues 015 (which seeded boat-services, home-cleaning, beauty-wellness).
-- This file seeds the next 7 roots × 9 locales:
--   1. renovation-construction
--   2. catering-food
--   3. tutoring-education
--   4. childcare-family
--   5. moving-transport
--   6. automotive
--   7. airbnb-management
--
-- Conventions (consistent with 015):
--   - weight 2: alternative noun / common term
--   - weight 3: domain term / jargon / specific service
--   - lowercase synonyms; query side normalizes to lower + unaccent
--   - Hibrit: loanword (e.g., 'catering') + native daily-speech together
--   - 9 locales each, ~12 syn/category (Arabic at parity)
--   - Boka Bay context (yacht/villa) for catering-food + airbnb-management
--   - Türk Budva diaspora idioms for tr (e.g., 'usta', 'ustam')
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. renovation-construction — Tadilat & İnşaat / Renovation & Construction
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('renovation-construction', 'me', 'renoviranje', 2),
  ('renovation-construction', 'me', 'adaptacija', 2),
  ('renovation-construction', 'me', 'gradnja', 2),
  ('renovation-construction', 'me', 'građevinski radovi', 3),
  ('renovation-construction', 'me', 'molerski radovi', 3),
  ('renovation-construction', 'me', 'moler', 2),
  ('renovation-construction', 'me', 'vodoinstalater', 2),
  ('renovation-construction', 'me', 'elektroinstalater', 2),
  ('renovation-construction', 'me', 'keramičar', 3),
  ('renovation-construction', 'me', 'gips kartonski radovi', 3),
  ('renovation-construction', 'me', 'fasada', 2),
  ('renovation-construction', 'me', 'majstor', 2),
  -- sr (Štokavian core mirrors me for trades)
  ('renovation-construction', 'sr', 'renoviranje', 2),
  ('renovation-construction', 'sr', 'adaptacija', 2),
  ('renovation-construction', 'sr', 'gradnja', 2),
  ('renovation-construction', 'sr', 'građevinski radovi', 3),
  ('renovation-construction', 'sr', 'molerski radovi', 3),
  ('renovation-construction', 'sr', 'moler', 2),
  ('renovation-construction', 'sr', 'vodoinstalater', 2),
  ('renovation-construction', 'sr', 'elektroinstalater', 2),
  ('renovation-construction', 'sr', 'keramičar', 3),
  ('renovation-construction', 'sr', 'gips kartonski radovi', 3),
  ('renovation-construction', 'sr', 'fasada', 2),
  ('renovation-construction', 'sr', 'majstor', 2),
  -- en
  ('renovation-construction', 'en', 'renovation', 2),
  ('renovation-construction', 'en', 'remodeling', 2),
  ('renovation-construction', 'en', 'construction', 2),
  ('renovation-construction', 'en', 'painting', 2),
  ('renovation-construction', 'en', 'painter', 2),
  ('renovation-construction', 'en', 'plumber', 2),
  ('renovation-construction', 'en', 'electrician', 2),
  ('renovation-construction', 'en', 'tiling', 3),
  ('renovation-construction', 'en', 'drywall', 3),
  ('renovation-construction', 'en', 'masonry', 3),
  ('renovation-construction', 'en', 'handyman', 2),
  ('renovation-construction', 'en', 'contractor', 2),
  -- tr
  ('renovation-construction', 'tr', 'tadilat', 2),
  ('renovation-construction', 'tr', 'yenileme', 2),
  ('renovation-construction', 'tr', 'inşaat', 2),
  ('renovation-construction', 'tr', 'boyama', 2),
  ('renovation-construction', 'tr', 'boyacı', 2),
  ('renovation-construction', 'tr', 'tesisatçı', 2),
  ('renovation-construction', 'tr', 'elektrikçi', 2),
  ('renovation-construction', 'tr', 'fayans ustası', 3),
  ('renovation-construction', 'tr', 'alçıpan', 3),
  ('renovation-construction', 'tr', 'duvar ustası', 3),
  ('renovation-construction', 'tr', 'çatı', 2),
  ('renovation-construction', 'tr', 'usta', 2),
  -- de
  ('renovation-construction', 'de', 'renovierung', 2),
  ('renovation-construction', 'de', 'umbau', 2),
  ('renovation-construction', 'de', 'bauarbeiten', 2),
  ('renovation-construction', 'de', 'maler', 2),
  ('renovation-construction', 'de', 'malerarbeiten', 2),
  ('renovation-construction', 'de', 'klempner', 2),
  ('renovation-construction', 'de', 'installateur', 2),
  ('renovation-construction', 'de', 'elektriker', 2),
  ('renovation-construction', 'de', 'fliesenleger', 3),
  ('renovation-construction', 'de', 'trockenbau', 3),
  ('renovation-construction', 'de', 'maurer', 3),
  ('renovation-construction', 'de', 'handwerker', 2),
  -- it
  ('renovation-construction', 'it', 'ristrutturazione', 2),
  ('renovation-construction', 'it', 'rinnovo', 2),
  ('renovation-construction', 'it', 'imbianchino', 2),
  ('renovation-construction', 'it', 'pittore', 2),
  ('renovation-construction', 'it', 'idraulico', 2),
  ('renovation-construction', 'it', 'elettricista', 2),
  ('renovation-construction', 'it', 'piastrellista', 3),
  ('renovation-construction', 'it', 'cartongesso', 3),
  ('renovation-construction', 'it', 'muratore', 3),
  ('renovation-construction', 'it', 'tuttofare', 2),
  ('renovation-construction', 'it', 'facciata', 2),
  ('renovation-construction', 'it', 'lavori edili', 2),
  -- ru
  ('renovation-construction', 'ru', 'ремонт', 2),
  ('renovation-construction', 'ru', 'реновация', 2),
  ('renovation-construction', 'ru', 'строительство', 2),
  ('renovation-construction', 'ru', 'маляр', 2),
  ('renovation-construction', 'ru', 'покраска', 2),
  ('renovation-construction', 'ru', 'сантехник', 2),
  ('renovation-construction', 'ru', 'электрик', 2),
  ('renovation-construction', 'ru', 'плиточник', 3),
  ('renovation-construction', 'ru', 'гипсокартон', 3),
  ('renovation-construction', 'ru', 'каменщик', 3),
  ('renovation-construction', 'ru', 'мастер', 2),
  ('renovation-construction', 'ru', 'кровля', 2),
  -- ar
  ('renovation-construction', 'ar', 'تجديد', 2),
  ('renovation-construction', 'ar', 'إعادة تأهيل', 2),
  ('renovation-construction', 'ar', 'بناء', 2),
  ('renovation-construction', 'ar', 'دهان', 2),
  ('renovation-construction', 'ar', 'نقاش', 2),
  ('renovation-construction', 'ar', 'سباك', 2),
  ('renovation-construction', 'ar', 'كهربائي', 2),
  ('renovation-construction', 'ar', 'بلاط', 3),
  ('renovation-construction', 'ar', 'جبس بورد', 3),
  ('renovation-construction', 'ar', 'عامل بناء', 3),
  ('renovation-construction', 'ar', 'أعمال صيانة', 3),
  ('renovation-construction', 'ar', 'ديكور داخلي', 3),
  -- uk
  ('renovation-construction', 'uk', 'ремонт', 2),
  ('renovation-construction', 'uk', 'ремонтні роботи', 2),
  ('renovation-construction', 'uk', 'будівництво', 2),
  ('renovation-construction', 'uk', 'маляр', 2),
  ('renovation-construction', 'uk', 'фарбування', 2),
  ('renovation-construction', 'uk', 'сантехнік', 2),
  ('renovation-construction', 'uk', 'електрик', 2),
  ('renovation-construction', 'uk', 'плиточник', 3),
  ('renovation-construction', 'uk', 'гіпсокартон', 3),
  ('renovation-construction', 'uk', 'муляр', 3),
  ('renovation-construction', 'uk', 'майстер', 2),
  ('renovation-construction', 'uk', 'покрівля', 2);


-- ----------------------------------------------------------------------------
-- 2. catering-food — Yemek & Catering / Catering & Food
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('catering-food', 'me', 'ketering', 2),
  ('catering-food', 'me', 'usluge ishrane', 3),
  ('catering-food', 'me', 'kuvanje', 2),
  ('catering-food', 'me', 'privatni kuvar', 3),
  ('catering-food', 'me', 'proslave', 2),
  ('catering-food', 'me', 'venčanja', 3),
  ('catering-food', 'me', 'roštilj', 2),
  ('catering-food', 'me', 'pečenje', 3),
  ('catering-food', 'me', 'jahta katering', 3),
  ('catering-food', 'me', 'vila katering', 3),
  ('catering-food', 'me', 'mediteranska kuhinja', 3),
  ('catering-food', 'me', 'bife', 2),
  -- sr
  ('catering-food', 'sr', 'ketering', 2),
  ('catering-food', 'sr', 'usluge ishrane', 3),
  ('catering-food', 'sr', 'kuvanje', 2),
  ('catering-food', 'sr', 'privatni kuvar', 3),
  ('catering-food', 'sr', 'proslave', 2),
  ('catering-food', 'sr', 'venčanja', 3),
  ('catering-food', 'sr', 'roštilj', 2),
  ('catering-food', 'sr', 'pečenje', 3),
  ('catering-food', 'sr', 'jahta katering', 3),
  ('catering-food', 'sr', 'vila katering', 3),
  ('catering-food', 'sr', 'mediteranska kuhinja', 3),
  ('catering-food', 'sr', 'bife', 2),
  -- en
  ('catering-food', 'en', 'catering', 2),
  ('catering-food', 'en', 'private chef', 3),
  ('catering-food', 'en', 'chef', 2),
  ('catering-food', 'en', 'caterer', 2),
  ('catering-food', 'en', 'event food', 3),
  ('catering-food', 'en', 'wedding catering', 3),
  ('catering-food', 'en', 'yacht catering', 3),
  ('catering-food', 'en', 'villa catering', 3),
  ('catering-food', 'en', 'bbq', 2),
  ('catering-food', 'en', 'mediterranean cuisine', 3),
  ('catering-food', 'en', 'buffet', 2),
  ('catering-food', 'en', 'canapes', 3),
  -- tr
  ('catering-food', 'tr', 'catering', 2),
  ('catering-food', 'tr', 'yemek servisi', 2),
  ('catering-food', 'tr', 'aşçı', 2),
  ('catering-food', 'tr', 'şef', 2),
  ('catering-food', 'tr', 'özel şef', 3),
  ('catering-food', 'tr', 'mangal', 2),
  ('catering-food', 'tr', 'düğün yemeği', 3),
  ('catering-food', 'tr', 'yat yemeği', 3),
  ('catering-food', 'tr', 'villa yemeği', 3),
  ('catering-food', 'tr', 'ikram', 2),
  ('catering-food', 'tr', 'büfe', 2),
  ('catering-food', 'tr', 'meze', 3),
  -- de
  ('catering-food', 'de', 'catering', 2),
  ('catering-food', 'de', 'partyservice', 2),
  ('catering-food', 'de', 'privatkoch', 3),
  ('catering-food', 'de', 'koch', 2),
  ('catering-food', 'de', 'caterer', 2),
  ('catering-food', 'de', 'event-catering', 3),
  ('catering-food', 'de', 'hochzeitscatering', 3),
  ('catering-food', 'de', 'yacht-catering', 3),
  ('catering-food', 'de', 'grillen', 2),
  ('catering-food', 'de', 'buffet', 2),
  ('catering-food', 'de', 'mediterrane küche', 3),
  ('catering-food', 'de', 'privatdiner', 3),
  -- it
  ('catering-food', 'it', 'catering', 2),
  ('catering-food', 'it', 'chef privato', 3),
  ('catering-food', 'it', 'cuoco', 2),
  ('catering-food', 'it', 'chef', 2),
  ('catering-food', 'it', 'ristorazione', 2),
  ('catering-food', 'it', 'buffet', 2),
  ('catering-food', 'it', 'catering matrimonio', 3),
  ('catering-food', 'it', 'catering yacht', 3),
  ('catering-food', 'it', 'catering villa', 3),
  ('catering-food', 'it', 'grigliata', 2),
  ('catering-food', 'it', 'cucina mediterranea', 3),
  ('catering-food', 'it', 'aperitivo', 3),
  -- ru
  ('catering-food', 'ru', 'кейтеринг', 2),
  ('catering-food', 'ru', 'частный повар', 3),
  ('catering-food', 'ru', 'повар', 2),
  ('catering-food', 'ru', 'шеф-повар', 2),
  ('catering-food', 'ru', 'обслуживание мероприятий', 3),
  ('catering-food', 'ru', 'свадебный кейтеринг', 3),
  ('catering-food', 'ru', 'кейтеринг на яхте', 3),
  ('catering-food', 'ru', 'барбекю', 2),
  ('catering-food', 'ru', 'мангал', 2),
  ('catering-food', 'ru', 'средиземноморская кухня', 3),
  ('catering-food', 'ru', 'фуршет', 2),
  ('catering-food', 'ru', 'банкет', 2),
  -- ar
  ('catering-food', 'ar', 'تموين', 2),
  ('catering-food', 'ar', 'خدمات طعام', 2),
  ('catering-food', 'ar', 'طاهي', 2),
  ('catering-food', 'ar', 'شيف خاص', 3),
  ('catering-food', 'ar', 'شيف', 2),
  ('catering-food', 'ar', 'حفلات زفاف', 3),
  ('catering-food', 'ar', 'ضيافة', 2),
  ('catering-food', 'ar', 'شواء', 2),
  ('catering-food', 'ar', 'بوفيه', 2),
  ('catering-food', 'ar', 'مطبخ متوسطي', 3),
  ('catering-food', 'ar', 'خدمة مأدبة', 3),
  ('catering-food', 'ar', 'خدمة الفلل', 3),
  -- uk
  ('catering-food', 'uk', 'кейтеринг', 2),
  ('catering-food', 'uk', 'приватний кухар', 3),
  ('catering-food', 'uk', 'кухар', 2),
  ('catering-food', 'uk', 'шеф-кухар', 2),
  ('catering-food', 'uk', 'обслуговування заходів', 3),
  ('catering-food', 'uk', 'весільний кейтеринг', 3),
  ('catering-food', 'uk', 'кейтеринг на яхті', 3),
  ('catering-food', 'uk', 'барбекю', 2),
  ('catering-food', 'uk', 'мангал', 2),
  ('catering-food', 'uk', 'середземноморська кухня', 3),
  ('catering-food', 'uk', 'фуршет', 2),
  ('catering-food', 'uk', 'бенкет', 2);


-- ----------------------------------------------------------------------------
-- 3. tutoring-education — Eğitim & Ders / Tutoring & Education
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('tutoring-education', 'me', 'privatni časovi', 2),
  ('tutoring-education', 'me', 'instrukcije', 3),
  ('tutoring-education', 'me', 'časovi engleskog', 3),
  ('tutoring-education', 'me', 'časovi matematike', 3),
  ('tutoring-education', 'me', 'profesor', 2),
  ('tutoring-education', 'me', 'nastavnik', 2),
  ('tutoring-education', 'me', 'jezici', 2),
  ('tutoring-education', 'me', 'muzička škola', 3),
  ('tutoring-education', 'me', 'časovi klavira', 3),
  ('tutoring-education', 'me', 'pomoć u učenju', 3),
  ('tutoring-education', 'me', 'priprema za maturu', 3),
  ('tutoring-education', 'me', 'auto škola', 3),
  -- sr
  ('tutoring-education', 'sr', 'privatni časovi', 2),
  ('tutoring-education', 'sr', 'instrukcije', 3),
  ('tutoring-education', 'sr', 'časovi engleskog', 3),
  ('tutoring-education', 'sr', 'časovi matematike', 3),
  ('tutoring-education', 'sr', 'profesor', 2),
  ('tutoring-education', 'sr', 'nastavnik', 2),
  ('tutoring-education', 'sr', 'jezici', 2),
  ('tutoring-education', 'sr', 'muzička škola', 3),
  ('tutoring-education', 'sr', 'časovi klavira', 3),
  ('tutoring-education', 'sr', 'pomoć u učenju', 3),
  ('tutoring-education', 'sr', 'priprema za maturu', 3),
  ('tutoring-education', 'sr', 'auto škola', 3),
  -- en
  ('tutoring-education', 'en', 'tutoring', 2),
  ('tutoring-education', 'en', 'private lessons', 2),
  ('tutoring-education', 'en', 'tutor', 2),
  ('tutoring-education', 'en', 'math tutor', 3),
  ('tutoring-education', 'en', 'english tutor', 3),
  ('tutoring-education', 'en', 'language lessons', 3),
  ('tutoring-education', 'en', 'music lessons', 3),
  ('tutoring-education', 'en', 'piano lessons', 3),
  ('tutoring-education', 'en', 'guitar lessons', 3),
  ('tutoring-education', 'en', 'homework help', 3),
  ('tutoring-education', 'en', 'exam prep', 3),
  ('tutoring-education', 'en', 'driving lessons', 3),
  -- tr
  ('tutoring-education', 'tr', 'özel ders', 2),
  ('tutoring-education', 'tr', 'ders', 2),
  ('tutoring-education', 'tr', 'ingilizce dersi', 3),
  ('tutoring-education', 'tr', 'matematik dersi', 3),
  ('tutoring-education', 'tr', 'müzik dersi', 3),
  ('tutoring-education', 'tr', 'piyano dersi', 3),
  ('tutoring-education', 'tr', 'öğretmen', 2),
  ('tutoring-education', 'tr', 'eğitmen', 2),
  ('tutoring-education', 'tr', 'dil kursu', 3),
  ('tutoring-education', 'tr', 'sürücü kursu', 3),
  ('tutoring-education', 'tr', 'ödev yardımı', 3),
  ('tutoring-education', 'tr', 'yks hazırlık', 3),
  -- de
  ('tutoring-education', 'de', 'nachhilfe', 2),
  ('tutoring-education', 'de', 'privatunterricht', 2),
  ('tutoring-education', 'de', 'privatlehrer', 2),
  ('tutoring-education', 'de', 'mathenachhilfe', 3),
  ('tutoring-education', 'de', 'englischunterricht', 3),
  ('tutoring-education', 'de', 'sprachkurs', 3),
  ('tutoring-education', 'de', 'musikunterricht', 3),
  ('tutoring-education', 'de', 'klavierunterricht', 3),
  ('tutoring-education', 'de', 'gitarrenunterricht', 3),
  ('tutoring-education', 'de', 'hausaufgabenhilfe', 3),
  ('tutoring-education', 'de', 'prüfungsvorbereitung', 3),
  ('tutoring-education', 'de', 'fahrschule', 3),
  -- it
  ('tutoring-education', 'it', 'ripetizioni', 2),
  ('tutoring-education', 'it', 'lezioni private', 2),
  ('tutoring-education', 'it', 'insegnante privato', 2),
  ('tutoring-education', 'it', 'ripetizioni matematica', 3),
  ('tutoring-education', 'it', 'lezioni inglese', 3),
  ('tutoring-education', 'it', 'corsi di lingua', 3),
  ('tutoring-education', 'it', 'lezioni di musica', 3),
  ('tutoring-education', 'it', 'lezioni di pianoforte', 3),
  ('tutoring-education', 'it', 'aiuto compiti', 3),
  ('tutoring-education', 'it', 'preparazione esami', 3),
  ('tutoring-education', 'it', 'doposcuola', 3),
  ('tutoring-education', 'it', 'autoscuola', 3),
  -- ru
  ('tutoring-education', 'ru', 'репетитор', 2),
  ('tutoring-education', 'ru', 'частные уроки', 2),
  ('tutoring-education', 'ru', 'занятия', 2),
  ('tutoring-education', 'ru', 'репетитор по математике', 3),
  ('tutoring-education', 'ru', 'репетитор по английскому', 3),
  ('tutoring-education', 'ru', 'уроки английского', 3),
  ('tutoring-education', 'ru', 'курсы языков', 3),
  ('tutoring-education', 'ru', 'уроки музыки', 3),
  ('tutoring-education', 'ru', 'уроки фортепиано', 3),
  ('tutoring-education', 'ru', 'помощь с домашним заданием', 3),
  ('tutoring-education', 'ru', 'подготовка к экзаменам', 3),
  ('tutoring-education', 'ru', 'автошкола', 3),
  -- ar
  ('tutoring-education', 'ar', 'دروس خصوصية', 2),
  ('tutoring-education', 'ar', 'معلم خاص', 2),
  ('tutoring-education', 'ar', 'مدرس', 2),
  ('tutoring-education', 'ar', 'دروس رياضيات', 3),
  ('tutoring-education', 'ar', 'دروس انجليزي', 3),
  ('tutoring-education', 'ar', 'دورات لغات', 3),
  ('tutoring-education', 'ar', 'دروس موسيقى', 3),
  ('tutoring-education', 'ar', 'دروس بيانو', 3),
  ('tutoring-education', 'ar', 'مساعدة في الواجبات', 3),
  ('tutoring-education', 'ar', 'تحضير للامتحانات', 3),
  ('tutoring-education', 'ar', 'تعليم القيادة', 3),
  ('tutoring-education', 'ar', 'معلمة', 2),
  -- uk
  ('tutoring-education', 'uk', 'репетитор', 2),
  ('tutoring-education', 'uk', 'приватні уроки', 2),
  ('tutoring-education', 'uk', 'вчитель', 2),
  ('tutoring-education', 'uk', 'репетитор з математики', 3),
  ('tutoring-education', 'uk', 'репетитор з англійської', 3),
  ('tutoring-education', 'uk', 'курси мов', 3),
  ('tutoring-education', 'uk', 'уроки музики', 3),
  ('tutoring-education', 'uk', 'уроки фортепіано', 3),
  ('tutoring-education', 'uk', 'допомога з домашнім завданням', 3),
  ('tutoring-education', 'uk', 'підготовка до іспитів', 3),
  ('tutoring-education', 'uk', 'коучинг', 2),
  ('tutoring-education', 'uk', 'автошкола', 3);


-- ----------------------------------------------------------------------------
-- 4. childcare-family — Çocuk & Aile / Childcare & Family
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('childcare-family', 'me', 'čuvanje djece', 2),
  ('childcare-family', 'me', 'bebisiterka', 2),
  ('childcare-family', 'me', 'dadilja', 2),
  ('childcare-family', 'me', 'vrtić', 2),
  ('childcare-family', 'me', 'jaslice', 3),
  ('childcare-family', 'me', 'čuvanje beba', 3),
  ('childcare-family', 'me', 'pomoć u domu sa djecom', 3),
  ('childcare-family', 'me', 'igraonica', 3),
  ('childcare-family', 'me', 'prevoz djece', 3),
  ('childcare-family', 'me', 'briga o starijima', 3),
  ('childcare-family', 'me', 'kućna pomoć', 2),
  ('childcare-family', 'me', 'au pair', 3),
  -- sr
  ('childcare-family', 'sr', 'čuvanje dece', 2),
  ('childcare-family', 'sr', 'bebisiterka', 2),
  ('childcare-family', 'sr', 'dadilja', 2),
  ('childcare-family', 'sr', 'vrtić', 2),
  ('childcare-family', 'sr', 'jaslice', 3),
  ('childcare-family', 'sr', 'čuvanje beba', 3),
  ('childcare-family', 'sr', 'pomoć u domu sa decom', 3),
  ('childcare-family', 'sr', 'igraonica', 3),
  ('childcare-family', 'sr', 'prevoz dece', 3),
  ('childcare-family', 'sr', 'briga o starijima', 3),
  ('childcare-family', 'sr', 'kućna pomoć', 2),
  ('childcare-family', 'sr', 'au pair', 3),
  -- en
  ('childcare-family', 'en', 'babysitting', 2),
  ('childcare-family', 'en', 'babysitter', 2),
  ('childcare-family', 'en', 'nanny', 2),
  ('childcare-family', 'en', 'childcare', 2),
  ('childcare-family', 'en', 'daycare', 2),
  ('childcare-family', 'en', 'nursery', 3),
  ('childcare-family', 'en', 'au pair', 3),
  ('childcare-family', 'en', 'after school care', 3),
  ('childcare-family', 'en', 'elderly care', 3),
  ('childcare-family', 'en', 'senior care', 3),
  ('childcare-family', 'en', 'caregiver', 2),
  ('childcare-family', 'en', 'home care', 2),
  -- tr
  ('childcare-family', 'tr', 'bebek bakıcısı', 2),
  ('childcare-family', 'tr', 'çocuk bakıcısı', 2),
  ('childcare-family', 'tr', 'çocuk bakımı', 2),
  ('childcare-family', 'tr', 'dadı', 2),
  ('childcare-family', 'tr', 'bakıcı', 2),
  ('childcare-family', 'tr', 'kreş', 2),
  ('childcare-family', 'tr', 'yuva', 3),
  ('childcare-family', 'tr', 'yaşlı bakımı', 3),
  ('childcare-family', 'tr', 'evde bakım', 3),
  ('childcare-family', 'tr', 'au pair', 3),
  ('childcare-family', 'tr', 'okul sonrası bakım', 3),
  ('childcare-family', 'tr', 'aile yardımcısı', 3),
  -- de
  ('childcare-family', 'de', 'kinderbetreuung', 2),
  ('childcare-family', 'de', 'babysitter', 2),
  ('childcare-family', 'de', 'tagesmutter', 3),
  ('childcare-family', 'de', 'kindermädchen', 2),
  ('childcare-family', 'de', 'au pair', 3),
  ('childcare-family', 'de', 'kita', 2),
  ('childcare-family', 'de', 'kindergarten', 2),
  ('childcare-family', 'de', 'nanny', 2),
  ('childcare-family', 'de', 'seniorenbetreuung', 3),
  ('childcare-family', 'de', 'altenpflege', 3),
  ('childcare-family', 'de', 'haushaltshilfe', 2),
  ('childcare-family', 'de', 'pflegehilfe', 3),
  -- it
  ('childcare-family', 'it', 'baby sitter', 2),
  ('childcare-family', 'it', 'tata', 2),
  ('childcare-family', 'it', 'assistenza bambini', 3),
  ('childcare-family', 'it', 'asilo nido', 3),
  ('childcare-family', 'it', 'au pair', 3),
  ('childcare-family', 'it', 'doposcuola bambini', 3),
  ('childcare-family', 'it', 'assistenza anziani', 3),
  ('childcare-family', 'it', 'badante', 3),
  ('childcare-family', 'it', 'aiuto domestico', 2),
  ('childcare-family', 'it', 'nido', 2),
  ('childcare-family', 'it', 'accompagnatore', 2),
  ('childcare-family', 'it', 'educatrice', 2),
  -- ru
  ('childcare-family', 'ru', 'няня', 2),
  ('childcare-family', 'ru', 'бэбиситтер', 2),
  ('childcare-family', 'ru', 'присмотр за детьми', 2),
  ('childcare-family', 'ru', 'сидеть с ребёнком', 2),
  ('childcare-family', 'ru', 'ясли', 3),
  ('childcare-family', 'ru', 'детский сад', 2),
  ('childcare-family', 'ru', 'помощь с детьми', 3),
  ('childcare-family', 'ru', 'уход за пожилыми', 3),
  ('childcare-family', 'ru', 'сиделка', 3),
  ('childcare-family', 'ru', 'помощница по хозяйству', 2),
  ('childcare-family', 'ru', 'ау пэр', 3),
  ('childcare-family', 'ru', 'няня для новорождённого', 3),
  -- ar
  ('childcare-family', 'ar', 'جليسة أطفال', 2),
  ('childcare-family', 'ar', 'مربية', 2),
  ('childcare-family', 'ar', 'رعاية أطفال', 2),
  ('childcare-family', 'ar', 'حضانة', 2),
  ('childcare-family', 'ar', 'روضة أطفال', 3),
  ('childcare-family', 'ar', 'رعاية مسنين', 3),
  ('childcare-family', 'ar', 'جليسة مسنين', 3),
  ('childcare-family', 'ar', 'مساعدة منزلية', 2),
  ('childcare-family', 'ar', 'مربية إنجليزية', 3),
  ('childcare-family', 'ar', 'توصيل أطفال', 3),
  ('childcare-family', 'ar', 'اهتمام بالرضع', 3),
  ('childcare-family', 'ar', 'دعم أسري', 3),
  -- uk
  ('childcare-family', 'uk', 'няня', 2),
  ('childcare-family', 'uk', 'бебіситер', 2),
  ('childcare-family', 'uk', 'догляд за дітьми', 2),
  ('childcare-family', 'uk', 'сидіти з дитиною', 2),
  ('childcare-family', 'uk', 'ясла', 3),
  ('childcare-family', 'uk', 'дитячий садок', 2),
  ('childcare-family', 'uk', 'допомога з дітьми', 3),
  ('childcare-family', 'uk', 'догляд за літніми', 3),
  ('childcare-family', 'uk', 'доглядальниця', 3),
  ('childcare-family', 'uk', 'помічниця по дому', 2),
  ('childcare-family', 'uk', 'ау пер', 3),
  ('childcare-family', 'uk', 'няня для немовлят', 3);


-- ----------------------------------------------------------------------------
-- 5. moving-transport — Nakliye & Transport / Moving & Transport
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('moving-transport', 'me', 'selidba', 2),
  ('moving-transport', 'me', 'preseljenje', 2),
  ('moving-transport', 'me', 'transport', 2),
  ('moving-transport', 'me', 'prevoz', 2),
  ('moving-transport', 'me', 'pakovanje', 3),
  ('moving-transport', 'me', 'transport namještaja', 3),
  ('moving-transport', 'me', 'transport klavira', 3),
  ('moving-transport', 'me', 'selidba u inostranstvo', 3),
  ('moving-transport', 'me', 'kombi prevoz', 3),
  ('moving-transport', 'me', 'isporuka', 2),
  ('moving-transport', 'me', 'kurirska služba', 3),
  ('moving-transport', 'me', 'iznajmljivanje kombija', 3),
  -- sr
  ('moving-transport', 'sr', 'selidba', 2),
  ('moving-transport', 'sr', 'preseljenje', 2),
  ('moving-transport', 'sr', 'transport', 2),
  ('moving-transport', 'sr', 'prevoz', 2),
  ('moving-transport', 'sr', 'pakovanje', 3),
  ('moving-transport', 'sr', 'transport nameštaja', 3),
  ('moving-transport', 'sr', 'transport klavira', 3),
  ('moving-transport', 'sr', 'selidba u inostranstvo', 3),
  ('moving-transport', 'sr', 'kombi prevoz', 3),
  ('moving-transport', 'sr', 'isporuka', 2),
  ('moving-transport', 'sr', 'kurirska služba', 3),
  ('moving-transport', 'sr', 'iznajmljivanje kombija', 3),
  -- en
  ('moving-transport', 'en', 'moving', 2),
  ('moving-transport', 'en', 'house moving', 2),
  ('moving-transport', 'en', 'relocation', 2),
  ('moving-transport', 'en', 'packing', 3),
  ('moving-transport', 'en', 'movers', 2),
  ('moving-transport', 'en', 'removal', 2),
  ('moving-transport', 'en', 'furniture moving', 3),
  ('moving-transport', 'en', 'piano moving', 3),
  ('moving-transport', 'en', 'international moving', 3),
  ('moving-transport', 'en', 'van rental', 3),
  ('moving-transport', 'en', 'courier', 2),
  ('moving-transport', 'en', 'delivery', 2),
  -- tr
  ('moving-transport', 'tr', 'nakliye', 2),
  ('moving-transport', 'tr', 'evden eve nakliyat', 2),
  ('moving-transport', 'tr', 'taşıma', 2),
  ('moving-transport', 'tr', 'şehirler arası nakliye', 3),
  ('moving-transport', 'tr', 'piyano taşıma', 3),
  ('moving-transport', 'tr', 'uluslararası nakliye', 3),
  ('moving-transport', 'tr', 'ambalajlama', 3),
  ('moving-transport', 'tr', 'ofis taşıma', 3),
  ('moving-transport', 'tr', 'kurye', 2),
  ('moving-transport', 'tr', 'kargo', 2),
  ('moving-transport', 'tr', 'minibüs nakliye', 3),
  ('moving-transport', 'tr', 'mobilya taşıma', 3),
  -- de
  ('moving-transport', 'de', 'umzug', 2),
  ('moving-transport', 'de', 'umzugsfirma', 2),
  ('moving-transport', 'de', 'möbeltransport', 3),
  ('moving-transport', 'de', 'klaviertransport', 3),
  ('moving-transport', 'de', 'internationaler umzug', 3),
  ('moving-transport', 'de', 'packdienst', 3),
  ('moving-transport', 'de', 'speditionsservice', 3),
  ('moving-transport', 'de', 'spedition', 2),
  ('moving-transport', 'de', 'kurierdienst', 3),
  ('moving-transport', 'de', 'transportservice', 3),
  ('moving-transport', 'de', 'lieferung', 2),
  ('moving-transport', 'de', 'transporter mieten', 3),
  -- it
  ('moving-transport', 'it', 'trasloco', 2),
  ('moving-transport', 'it', 'trasporti', 2),
  ('moving-transport', 'it', 'impresa di traslochi', 2),
  ('moving-transport', 'it', 'imballaggio', 3),
  ('moving-transport', 'it', 'trasporto mobili', 3),
  ('moving-transport', 'it', 'trasporto pianoforte', 3),
  ('moving-transport', 'it', 'trasloco internazionale', 3),
  ('moving-transport', 'it', 'noleggio furgoni', 3),
  ('moving-transport', 'it', 'corriere', 2),
  ('moving-transport', 'it', 'spedizione', 2),
  ('moving-transport', 'it', 'consegna', 2),
  ('moving-transport', 'it', 'trasportatore', 2),
  -- ru
  ('moving-transport', 'ru', 'переезд', 2),
  ('moving-transport', 'ru', 'грузоперевозки', 2),
  ('moving-transport', 'ru', 'транспортировка', 2),
  ('moving-transport', 'ru', 'упаковка', 3),
  ('moving-transport', 'ru', 'перевозка мебели', 3),
  ('moving-transport', 'ru', 'перевозка пианино', 3),
  ('moving-transport', 'ru', 'международный переезд', 3),
  ('moving-transport', 'ru', 'грузчики', 3),
  ('moving-transport', 'ru', 'доставка', 2),
  ('moving-transport', 'ru', 'курьерская служба', 3),
  ('moving-transport', 'ru', 'аренда фургона', 3),
  ('moving-transport', 'ru', 'грузовое такси', 3),
  -- ar
  ('moving-transport', 'ar', 'نقل', 2),
  ('moving-transport', 'ar', 'نقل أثاث', 2),
  ('moving-transport', 'ar', 'شركة نقل', 2),
  ('moving-transport', 'ar', 'نقل دولي', 3),
  ('moving-transport', 'ar', 'نقل بيانو', 3),
  ('moving-transport', 'ar', 'تغليف', 3),
  ('moving-transport', 'ar', 'خدمة توصيل', 2),
  ('moving-transport', 'ar', 'شحن', 2),
  ('moving-transport', 'ar', 'تأجير شاحنة', 3),
  ('moving-transport', 'ar', 'نقل إلى الخارج', 3),
  ('moving-transport', 'ar', 'نقل مكتبي', 3),
  ('moving-transport', 'ar', 'خدمة شحن سريعة', 3),
  -- uk
  ('moving-transport', 'uk', 'переїзд', 2),
  ('moving-transport', 'uk', 'вантажоперевезення', 2),
  ('moving-transport', 'uk', 'транспортування', 2),
  ('moving-transport', 'uk', 'пакування', 3),
  ('moving-transport', 'uk', 'перевезення меблів', 3),
  ('moving-transport', 'uk', 'перевезення піаніно', 3),
  ('moving-transport', 'uk', 'міжнародний переїзд', 3),
  ('moving-transport', 'uk', 'вантажники', 3),
  ('moving-transport', 'uk', 'доставка', 2),
  ('moving-transport', 'uk', 'кур''єрська служба', 3),
  ('moving-transport', 'uk', 'оренда фургону', 3),
  ('moving-transport', 'uk', 'вантажне таксі', 3);


-- ----------------------------------------------------------------------------
-- 6. automotive — Otomotiv / Automotive
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('automotive', 'me', 'automehaničar', 2),
  ('automotive', 'me', 'servis automobila', 2),
  ('automotive', 'me', 'popravka auta', 2),
  ('automotive', 'me', 'mehaničar', 2),
  ('automotive', 'me', 'limarija', 3),
  ('automotive', 'me', 'farbanje auta', 3),
  ('automotive', 'me', 'vulkanizer', 3),
  ('automotive', 'me', 'gume', 2),
  ('automotive', 'me', 'promena gume', 3),
  ('automotive', 'me', 'pranje auta', 2),
  ('automotive', 'me', 'auto-električar', 3),
  ('automotive', 'me', 'detailing', 3),
  -- sr
  ('automotive', 'sr', 'automehaničar', 2),
  ('automotive', 'sr', 'servis automobila', 2),
  ('automotive', 'sr', 'popravka auta', 2),
  ('automotive', 'sr', 'mehaničar', 2),
  ('automotive', 'sr', 'limarija', 3),
  ('automotive', 'sr', 'farbanje auta', 3),
  ('automotive', 'sr', 'vulkanizer', 3),
  ('automotive', 'sr', 'gume', 2),
  ('automotive', 'sr', 'promena gume', 3),
  ('automotive', 'sr', 'pranje auta', 2),
  ('automotive', 'sr', 'auto-električar', 3),
  ('automotive', 'sr', 'detailing', 3),
  -- en
  ('automotive', 'en', 'auto repair', 2),
  ('automotive', 'en', 'mechanic', 2),
  ('automotive', 'en', 'car service', 2),
  ('automotive', 'en', 'car repair', 2),
  ('automotive', 'en', 'body shop', 3),
  ('automotive', 'en', 'tire change', 3),
  ('automotive', 'en', 'tire repair', 3),
  ('automotive', 'en', 'detailing', 3),
  ('automotive', 'en', 'car wash', 2),
  ('automotive', 'en', 'auto electrician', 3),
  ('automotive', 'en', 'oil change', 3),
  ('automotive', 'en', 'vehicle inspection', 3),
  -- tr
  ('automotive', 'tr', 'oto tamiri', 2),
  ('automotive', 'tr', 'oto servisi', 2),
  ('automotive', 'tr', 'tamirci', 2),
  ('automotive', 'tr', 'kaporta', 3),
  ('automotive', 'tr', 'oto boyacı', 3),
  ('automotive', 'tr', 'lastikçi', 3),
  ('automotive', 'tr', 'lastik değişimi', 3),
  ('automotive', 'tr', 'yağ değişimi', 3),
  ('automotive', 'tr', 'oto yıkama', 2),
  ('automotive', 'tr', 'detailing', 3),
  ('automotive', 'tr', 'muayene', 2),
  ('automotive', 'tr', 'akü', 3),
  -- de
  ('automotive', 'de', 'kfz-werkstatt', 2),
  ('automotive', 'de', 'automechaniker', 2),
  ('automotive', 'de', 'autoservice', 2),
  ('automotive', 'de', 'autoreparatur', 2),
  ('automotive', 'de', 'karosserie', 3),
  ('automotive', 'de', 'lackiererei', 3),
  ('automotive', 'de', 'reifenwechsel', 3),
  ('automotive', 'de', 'reifenservice', 3),
  ('automotive', 'de', 'autowäsche', 2),
  ('automotive', 'de', 'detailing', 3),
  ('automotive', 'de', 'ölwechsel', 3),
  ('automotive', 'de', 'tüv', 3),
  -- it
  ('automotive', 'it', 'meccanico', 2),
  ('automotive', 'it', 'officina', 2),
  ('automotive', 'it', 'riparazione auto', 2),
  ('automotive', 'it', 'carrozzeria', 3),
  ('automotive', 'it', 'gommista', 3),
  ('automotive', 'it', 'cambio gomme', 3),
  ('automotive', 'it', 'cambio olio', 3),
  ('automotive', 'it', 'lavaggio auto', 2),
  ('automotive', 'it', 'detailing', 3),
  ('automotive', 'it', 'elettrauto', 3),
  ('automotive', 'it', 'revisione auto', 3),
  ('automotive', 'it', 'batteria', 2),
  -- ru
  ('automotive', 'ru', 'автосервис', 2),
  ('automotive', 'ru', 'автомеханик', 2),
  ('automotive', 'ru', 'ремонт авто', 2),
  ('automotive', 'ru', 'ремонт автомобилей', 2),
  ('automotive', 'ru', 'кузовной ремонт', 3),
  ('automotive', 'ru', 'покраска авто', 3),
  ('automotive', 'ru', 'шиномонтаж', 3),
  ('automotive', 'ru', 'замена шин', 3),
  ('automotive', 'ru', 'замена масла', 3),
  ('automotive', 'ru', 'мойка авто', 2),
  ('automotive', 'ru', 'автоэлектрик', 3),
  ('automotive', 'ru', 'технический осмотр', 3),
  -- ar
  ('automotive', 'ar', 'ميكانيكي', 2),
  ('automotive', 'ar', 'ورشة سيارات', 2),
  ('automotive', 'ar', 'تصليح سيارات', 2),
  ('automotive', 'ar', 'خدمة سيارات', 2),
  ('automotive', 'ar', 'سمكرة سيارات', 3),
  ('automotive', 'ar', 'صباغة سيارات', 3),
  ('automotive', 'ar', 'تبديل إطارات', 3),
  ('automotive', 'ar', 'تغيير زيت', 3),
  ('automotive', 'ar', 'غسيل سيارات', 2),
  ('automotive', 'ar', 'ديتيلنغ', 3),
  ('automotive', 'ar', 'كهربائي سيارات', 3),
  ('automotive', 'ar', 'فحص فني', 3),
  -- uk
  ('automotive', 'uk', 'автосервіс', 2),
  ('automotive', 'uk', 'автомеханік', 2),
  ('automotive', 'uk', 'ремонт авто', 2),
  ('automotive', 'uk', 'ремонт автомобілів', 2),
  ('automotive', 'uk', 'кузовний ремонт', 3),
  ('automotive', 'uk', 'фарбування авто', 3),
  ('automotive', 'uk', 'шиномонтаж', 3),
  ('automotive', 'uk', 'заміна шин', 3),
  ('automotive', 'uk', 'заміна масла', 3),
  ('automotive', 'uk', 'мийка авто', 2),
  ('automotive', 'uk', 'автоелектрик', 3),
  ('automotive', 'uk', 'технічний огляд', 3);


-- ----------------------------------------------------------------------------
-- 7. airbnb-management — Airbnb İşletme / Airbnb Management
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  -- me
  ('airbnb-management', 'me', 'airbnb', 2),
  ('airbnb-management', 'me', 'upravljanje smještajem', 2),
  ('airbnb-management', 'me', 'kratkoročni najam', 3),
  ('airbnb-management', 'me', 'iznajmljivanje vile', 3),
  ('airbnb-management', 'me', 'upravljanje vilom', 3),
  ('airbnb-management', 'me', 'predaja ključeva', 3),
  ('airbnb-management', 'me', 'čišćenje između gostiju', 3),
  ('airbnb-management', 'me', 'domaćin', 2),
  ('airbnb-management', 'me', 'co-host', 3),
  ('airbnb-management', 'me', 'prijava gostiju', 3),
  ('airbnb-management', 'me', 'usluge za goste', 3),
  ('airbnb-management', 'me', 'upravljanje booking-om', 3),
  -- sr
  ('airbnb-management', 'sr', 'airbnb', 2),
  ('airbnb-management', 'sr', 'upravljanje smeštajem', 2),
  ('airbnb-management', 'sr', 'kratkoročni najam', 3),
  ('airbnb-management', 'sr', 'iznajmljivanje vile', 3),
  ('airbnb-management', 'sr', 'upravljanje vilom', 3),
  ('airbnb-management', 'sr', 'predaja ključeva', 3),
  ('airbnb-management', 'sr', 'čišćenje između gostiju', 3),
  ('airbnb-management', 'sr', 'domaćin', 2),
  ('airbnb-management', 'sr', 'co-host', 3),
  ('airbnb-management', 'sr', 'prijava gostiju', 3),
  ('airbnb-management', 'sr', 'usluge za goste', 3),
  ('airbnb-management', 'sr', 'upravljanje booking-om', 3),
  -- en
  ('airbnb-management', 'en', 'airbnb', 2),
  ('airbnb-management', 'en', 'airbnb management', 2),
  ('airbnb-management', 'en', 'short-term rental', 2),
  ('airbnb-management', 'en', 'vacation rental', 2),
  ('airbnb-management', 'en', 'vrbo', 3),
  ('airbnb-management', 'en', 'booking management', 3),
  ('airbnb-management', 'en', 'property management', 2),
  ('airbnb-management', 'en', 'co-host', 3),
  ('airbnb-management', 'en', 'guest check-in', 3),
  ('airbnb-management', 'en', 'key handover', 3),
  ('airbnb-management', 'en', 'turnover cleaning', 3),
  ('airbnb-management', 'en', 'str manager', 3),
  -- tr
  ('airbnb-management', 'tr', 'airbnb', 2),
  ('airbnb-management', 'tr', 'airbnb yönetimi', 2),
  ('airbnb-management', 'tr', 'günlük kiralama', 3),
  ('airbnb-management', 'tr', 'kısa dönem kiralama', 3),
  ('airbnb-management', 'tr', 'villa kiralama', 3),
  ('airbnb-management', 'tr', 'villa yönetimi', 3),
  ('airbnb-management', 'tr', 'konuk teslim', 3),
  ('airbnb-management', 'tr', 'anahtar teslim', 3),
  ('airbnb-management', 'tr', 'giriş çıkış temizliği', 3),
  ('airbnb-management', 'tr', 'ev sahibi', 2),
  ('airbnb-management', 'tr', 'konaklama yönetimi', 2),
  ('airbnb-management', 'tr', 'rezervasyon yönetimi', 3),
  -- de
  ('airbnb-management', 'de', 'airbnb', 2),
  ('airbnb-management', 'de', 'airbnb verwaltung', 2),
  ('airbnb-management', 'de', 'ferienwohnung', 2),
  ('airbnb-management', 'de', 'ferienhaus', 2),
  ('airbnb-management', 'de', 'kurzzeitvermietung', 3),
  ('airbnb-management', 'de', 'co-host', 3),
  ('airbnb-management', 'de', 'gastgeber', 2),
  ('airbnb-management', 'de', 'schlüsselübergabe', 3),
  ('airbnb-management', 'de', 'check-in service', 3),
  ('airbnb-management', 'de', 'reinigung zwischen gästen', 3),
  ('airbnb-management', 'de', 'buchungsverwaltung', 3),
  ('airbnb-management', 'de', 'objektverwaltung', 2),
  -- it
  ('airbnb-management', 'it', 'airbnb', 2),
  ('airbnb-management', 'it', 'gestione airbnb', 2),
  ('airbnb-management', 'it', 'affitto breve', 3),
  ('airbnb-management', 'it', 'locazione turistica', 3),
  ('airbnb-management', 'it', 'co-host', 3),
  ('airbnb-management', 'it', 'gestione casa vacanze', 3),
  ('airbnb-management', 'it', 'check-in ospiti', 3),
  ('airbnb-management', 'it', 'consegna chiavi', 3),
  ('airbnb-management', 'it', 'pulizia turn-over', 3),
  ('airbnb-management', 'it', 'proprietario', 2),
  ('airbnb-management', 'it', 'affittacamere', 3),
  ('airbnb-management', 'it', 'gestione prenotazioni', 3),
  -- ru
  ('airbnb-management', 'ru', 'airbnb', 2),
  ('airbnb-management', 'ru', 'управление airbnb', 2),
  ('airbnb-management', 'ru', 'посуточная аренда', 3),
  ('airbnb-management', 'ru', 'краткосрочная аренда', 3),
  ('airbnb-management', 'ru', 'сдача виллы', 3),
  ('airbnb-management', 'ru', 'управление виллой', 3),
  ('airbnb-management', 'ru', 'передача ключей', 3),
  ('airbnb-management', 'ru', 'хост', 2),
  ('airbnb-management', 'ru', 'ко-хост', 3),
  ('airbnb-management', 'ru', 'встреча гостей', 3),
  ('airbnb-management', 'ru', 'уборка между гостями', 3),
  ('airbnb-management', 'ru', 'управление бронированиями', 3),
  -- ar
  ('airbnb-management', 'ar', 'ايربنب', 2),
  ('airbnb-management', 'ar', 'إدارة إيربنب', 2),
  ('airbnb-management', 'ar', 'تأجير قصير الأمد', 3),
  ('airbnb-management', 'ar', 'تأجير فيلا', 3),
  ('airbnb-management', 'ar', 'إدارة فيلا', 3),
  ('airbnb-management', 'ar', 'تسليم مفاتيح', 3),
  ('airbnb-management', 'ar', 'استقبال ضيوف', 3),
  ('airbnb-management', 'ar', 'تنظيف بين الضيوف', 3),
  ('airbnb-management', 'ar', 'مضيف', 2),
  ('airbnb-management', 'ar', 'إدارة عقارات', 2),
  ('airbnb-management', 'ar', 'إدارة حجوزات', 3),
  ('airbnb-management', 'ar', 'شقق سياحية', 3),
  -- uk
  ('airbnb-management', 'uk', 'airbnb', 2),
  ('airbnb-management', 'uk', 'управління airbnb', 2),
  ('airbnb-management', 'uk', 'подобова оренда', 3),
  ('airbnb-management', 'uk', 'короткострокова оренда', 3),
  ('airbnb-management', 'uk', 'здача вілли', 3),
  ('airbnb-management', 'uk', 'управління віллою', 3),
  ('airbnb-management', 'uk', 'передача ключів', 3),
  ('airbnb-management', 'uk', 'хост', 2),
  ('airbnb-management', 'uk', 'ко-хост', 3),
  ('airbnb-management', 'uk', 'зустріч гостей', 3),
  ('airbnb-management', 'uk', 'прибирання між гостями', 3),
  ('airbnb-management', 'uk', 'управління бронюваннями', 3);

COMMIT;
