-- ============================================================================
-- 018_glatko_search_synonyms_seed_batch2.sql
-- G-CAT-3: Sectoral synonym seed — BATCH 2 (boat-services sub-categories)
--
-- 8 sub-categories under boat-services:
--   1. hull-cleaning           — Tekne Dibi Temizliği / Pranje korita
--   2. antifouling             — Antifouling
--   3. boat-engine-service     — Tekne Motor Servisi
--   4. captain-daily           — Günlük Kaptan
--   5. winter-storage          — Kışlama Hizmeti
--   6. charter-cleaning        — Charter Teslim Temizliği
--   7. electrical-electronics  — Elektronik
--   8. sail-canvas             — Yelken Branda / Jedra i platno
--
-- Conventions: weight 3 (sub-categories are inherently jargon/specific
-- service); 5-6 syn per locale; brand names (Mercury/Yamaha) included for
-- engine service since users often search by brand.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. hull-cleaning
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('hull-cleaning', 'me', 'pranje trupa', 3),
  ('hull-cleaning', 'me', 'ronilac za čišćenje', 3),
  ('hull-cleaning', 'me', 'čišćenje obraštaja', 3),
  ('hull-cleaning', 'me', 'skidanje obraštaja', 3),
  ('hull-cleaning', 'me', 'podvodno čišćenje', 3),
  ('hull-cleaning', 'sr', 'pranje trupa', 3),
  ('hull-cleaning', 'sr', 'ronilac za čišćenje', 3),
  ('hull-cleaning', 'sr', 'čišćenje obraštaja', 3),
  ('hull-cleaning', 'sr', 'skidanje obraštaja', 3),
  ('hull-cleaning', 'sr', 'podvodno čišćenje', 3),
  ('hull-cleaning', 'en', 'hull cleaning', 3),
  ('hull-cleaning', 'en', 'bottom cleaning', 3),
  ('hull-cleaning', 'en', 'hull scrub', 3),
  ('hull-cleaning', 'en', 'diver cleaning', 3),
  ('hull-cleaning', 'en', 'underwater cleaning', 3),
  ('hull-cleaning', 'en', 'fouling removal', 3),
  ('hull-cleaning', 'tr', 'tekne dibi temizliği', 3),
  ('hull-cleaning', 'tr', 'karina temizliği', 3),
  ('hull-cleaning', 'tr', 'dalgıçla temizlik', 3),
  ('hull-cleaning', 'tr', 'su altı temizliği', 3),
  ('hull-cleaning', 'tr', 'obraşta temizliği', 3),
  ('hull-cleaning', 'de', 'rumpfreinigung', 3),
  ('hull-cleaning', 'de', 'unterwasserreinigung', 3),
  ('hull-cleaning', 'de', 'bewuchsentfernung', 3),
  ('hull-cleaning', 'de', 'bootsrumpf reinigen', 3),
  ('hull-cleaning', 'de', 'taucher reinigung', 3),
  ('hull-cleaning', 'it', 'pulizia carena', 3),
  ('hull-cleaning', 'it', 'pulizia subacquea', 3),
  ('hull-cleaning', 'it', 'pulizia scafo', 3),
  ('hull-cleaning', 'it', 'rimozione vegetazione', 3),
  ('hull-cleaning', 'it', 'subacqueo pulizia', 3),
  ('hull-cleaning', 'ru', 'чистка днища', 3),
  ('hull-cleaning', 'ru', 'чистка корпуса лодки', 3),
  ('hull-cleaning', 'ru', 'подводная чистка', 3),
  ('hull-cleaning', 'ru', 'удаление обрастания', 3),
  ('hull-cleaning', 'ru', 'водолаз чистка', 3),
  ('hull-cleaning', 'ar', 'تنظيف هيكل القارب', 3),
  ('hull-cleaning', 'ar', 'تنظيف تحت الماء', 3),
  ('hull-cleaning', 'ar', 'إزالة الحشف', 3),
  ('hull-cleaning', 'ar', 'غواص تنظيف', 3),
  ('hull-cleaning', 'ar', 'تنظيف قاع السفينة', 3),
  ('hull-cleaning', 'uk', 'чистка днища', 3),
  ('hull-cleaning', 'uk', 'чистка корпусу човна', 3),
  ('hull-cleaning', 'uk', 'підводна чистка', 3),
  ('hull-cleaning', 'uk', 'видалення обростання', 3),
  ('hull-cleaning', 'uk', 'водолаз чистка', 3);


-- ----------------------------------------------------------------------------
-- 2. antifouling
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('antifouling', 'me', 'premaz protiv obraštaja', 3),
  ('antifouling', 'me', 'antifouling premaz', 3),
  ('antifouling', 'me', 'zaštitni premaz dna', 3),
  ('antifouling', 'me', 'bojenje karine', 3),
  ('antifouling', 'me', 'antikorozivni premaz', 3),
  ('antifouling', 'sr', 'premaz protiv obraštaja', 3),
  ('antifouling', 'sr', 'antifouling premaz', 3),
  ('antifouling', 'sr', 'zaštitni premaz dna', 3),
  ('antifouling', 'sr', 'bojenje karine', 3),
  ('antifouling', 'sr', 'antikorozivni premaz', 3),
  ('antifouling', 'en', 'antifouling paint', 3),
  ('antifouling', 'en', 'bottom paint', 3),
  ('antifouling', 'en', 'hull paint', 3),
  ('antifouling', 'en', 'antifoul', 3),
  ('antifouling', 'en', 'copper paint', 3),
  ('antifouling', 'tr', 'zehirli boya', 3),
  ('antifouling', 'tr', 'tekne dibi boyası', 3),
  ('antifouling', 'tr', 'antifouling boya', 3),
  ('antifouling', 'tr', 'karina boyası', 3),
  ('antifouling', 'tr', 'alt boya', 3),
  ('antifouling', 'de', 'antifoulinganstrich', 3),
  ('antifouling', 'de', 'antifouling-farbe', 3),
  ('antifouling', 'de', 'bootsbodenanstrich', 3),
  ('antifouling', 'de', 'unterwasseranstrich', 3),
  ('antifouling', 'de', 'kupferfarbe', 3),
  ('antifouling', 'it', 'vernice antivegetativa', 3),
  ('antifouling', 'it', 'antifouling vernice', 3),
  ('antifouling', 'it', 'pittura carena', 3),
  ('antifouling', 'it', 'vernice sottomarina', 3),
  ('antifouling', 'it', 'pittura al rame', 3),
  ('antifouling', 'ru', 'антифоулинговая краска', 3),
  ('antifouling', 'ru', 'противообрастающая краска', 3),
  ('antifouling', 'ru', 'покраска днища', 3),
  ('antifouling', 'ru', 'покраска корпуса', 3),
  ('antifouling', 'ru', 'медная краска', 3),
  ('antifouling', 'ar', 'طلاء مضاد للحشف', 3),
  ('antifouling', 'ar', 'طلاء مضاد للأعشاب البحرية', 3),
  ('antifouling', 'ar', 'طلاء قاع القارب', 3),
  ('antifouling', 'ar', 'طلاء نحاسي', 3),
  ('antifouling', 'ar', 'طلاء قارب', 3),
  ('antifouling', 'uk', 'антифаулінгова фарба', 3),
  ('antifouling', 'uk', 'протиобростаюча фарба', 3),
  ('antifouling', 'uk', 'фарбування днища', 3),
  ('antifouling', 'uk', 'фарбування корпусу', 3),
  ('antifouling', 'uk', 'мідна фарба', 3);


-- ----------------------------------------------------------------------------
-- 3. boat-engine-service (incl. brand names: Mercury, Yamaha)
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('boat-engine-service', 'me', 'servis motora plovila', 3),
  ('boat-engine-service', 'me', 'popravka motora plovila', 3),
  ('boat-engine-service', 'me', 'vanbrodski motor', 3),
  ('boat-engine-service', 'me', 'mercury servis', 3),
  ('boat-engine-service', 'me', 'yamaha servis', 3),
  ('boat-engine-service', 'sr', 'servis motora plovila', 3),
  ('boat-engine-service', 'sr', 'popravka motora plovila', 3),
  ('boat-engine-service', 'sr', 'vanbrodski motor', 3),
  ('boat-engine-service', 'sr', 'mercury servis', 3),
  ('boat-engine-service', 'sr', 'yamaha servis', 3),
  ('boat-engine-service', 'en', 'engine service', 3),
  ('boat-engine-service', 'en', 'outboard service', 3),
  ('boat-engine-service', 'en', 'inboard service', 3),
  ('boat-engine-service', 'en', 'engine repair', 3),
  ('boat-engine-service', 'en', 'mercury service', 3),
  ('boat-engine-service', 'en', 'yamaha service', 3),
  ('boat-engine-service', 'tr', 'tekne motor servisi', 3),
  ('boat-engine-service', 'tr', 'yat motoru servisi', 3),
  ('boat-engine-service', 'tr', 'vanbordo motor', 3),
  ('boat-engine-service', 'tr', 'motor revizyonu', 3),
  ('boat-engine-service', 'tr', 'mercury servisi', 3),
  ('boat-engine-service', 'de', 'bootsmotor service', 3),
  ('boat-engine-service', 'de', 'außenbordmotor', 3),
  ('boat-engine-service', 'de', 'innenbordmotor', 3),
  ('boat-engine-service', 'de', 'motorreparatur boot', 3),
  ('boat-engine-service', 'de', 'mercury service', 3),
  ('boat-engine-service', 'it', 'motore barca', 3),
  ('boat-engine-service', 'it', 'motore fuoribordo', 3),
  ('boat-engine-service', 'it', 'motore entrobordo', 3),
  ('boat-engine-service', 'it', 'riparazione motore barca', 3),
  ('boat-engine-service', 'it', 'manutenzione motore', 3),
  ('boat-engine-service', 'ru', 'двигатель лодки', 3),
  ('boat-engine-service', 'ru', 'ремонт лодочного мотора', 3),
  ('boat-engine-service', 'ru', 'подвесной мотор', 3),
  ('boat-engine-service', 'ru', 'стационарный мотор', 3),
  ('boat-engine-service', 'ru', 'сервис меркури', 3),
  ('boat-engine-service', 'ar', 'صيانة محرك القارب', 3),
  ('boat-engine-service', 'ar', 'محرك خارجي', 3),
  ('boat-engine-service', 'ar', 'محرك داخلي', 3),
  ('boat-engine-service', 'ar', 'إصلاح محرك بحري', 3),
  ('boat-engine-service', 'ar', 'خدمة محرك مركوري', 3),
  ('boat-engine-service', 'uk', 'ремонт двигуна човна', 3),
  ('boat-engine-service', 'uk', 'підвісний мотор', 3),
  ('boat-engine-service', 'uk', 'стаціонарний мотор', 3),
  ('boat-engine-service', 'uk', 'обслуговування мотора', 3),
  ('boat-engine-service', 'uk', 'сервіс меркюрі', 3);


-- ----------------------------------------------------------------------------
-- 4. captain-daily
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('captain-daily', 'me', 'dnevni kapetan', 3),
  ('captain-daily', 'me', 'iznajmljivanje kapetana', 3),
  ('captain-daily', 'me', 'kapetan jahte', 3),
  ('captain-daily', 'me', 'skipper', 3),
  ('captain-daily', 'me', 'najam kapetana', 3),
  ('captain-daily', 'sr', 'dnevni kapetan', 3),
  ('captain-daily', 'sr', 'iznajmljivanje kapetana', 3),
  ('captain-daily', 'sr', 'kapetan jahte', 3),
  ('captain-daily', 'sr', 'skipper', 3),
  ('captain-daily', 'sr', 'najam kapetana', 3),
  ('captain-daily', 'en', 'daily captain', 3),
  ('captain-daily', 'en', 'skipper for hire', 3),
  ('captain-daily', 'en', 'yacht captain', 3),
  ('captain-daily', 'en', 'captain rental', 3),
  ('captain-daily', 'en', 'private skipper', 3),
  ('captain-daily', 'tr', 'günlük kaptan', 3),
  ('captain-daily', 'tr', 'kaptan kiralama', 3),
  ('captain-daily', 'tr', 'yat kaptanı', 3),
  ('captain-daily', 'tr', 'skipper', 3),
  ('captain-daily', 'tr', 'özel kaptan', 3),
  ('captain-daily', 'de', 'tageskapitän', 3),
  ('captain-daily', 'de', 'skipper buchen', 3),
  ('captain-daily', 'de', 'yachtkapitän', 3),
  ('captain-daily', 'de', 'kapitän mieten', 3),
  ('captain-daily', 'de', 'charterskipper', 3),
  ('captain-daily', 'it', 'capitano giornaliero', 3),
  ('captain-daily', 'it', 'skipper a noleggio', 3),
  ('captain-daily', 'it', 'capitano yacht', 3),
  ('captain-daily', 'it', 'noleggio capitano', 3),
  ('captain-daily', 'it', 'skipper privato', 3),
  ('captain-daily', 'ru', 'капитан на день', 3),
  ('captain-daily', 'ru', 'аренда капитана', 3),
  ('captain-daily', 'ru', 'капитан яхты', 3),
  ('captain-daily', 'ru', 'шкипер', 3),
  ('captain-daily', 'ru', 'частный капитан', 3),
  ('captain-daily', 'ar', 'قبطان يومي', 3),
  ('captain-daily', 'ar', 'استئجار قبطان', 3),
  ('captain-daily', 'ar', 'قبطان يخت', 3),
  ('captain-daily', 'ar', 'سكيبر', 3),
  ('captain-daily', 'ar', 'قبطان خاص', 3),
  ('captain-daily', 'uk', 'капітан на день', 3),
  ('captain-daily', 'uk', 'оренда капітана', 3),
  ('captain-daily', 'uk', 'капітан яхти', 3),
  ('captain-daily', 'uk', 'шкіпер', 3),
  ('captain-daily', 'uk', 'приватний капітан', 3);


-- ----------------------------------------------------------------------------
-- 5. winter-storage
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('winter-storage', 'me', 'zimovanje plovila', 3),
  ('winter-storage', 'me', 'skladištenje preko zime', 3),
  ('winter-storage', 'me', 'zimska zaštita', 3),
  ('winter-storage', 'me', 'haul-out servis', 3),
  ('winter-storage', 'me', 'vađenje plovila iz vode', 3),
  ('winter-storage', 'sr', 'zimovanje plovila', 3),
  ('winter-storage', 'sr', 'skladištenje preko zime', 3),
  ('winter-storage', 'sr', 'zimska zaštita', 3),
  ('winter-storage', 'sr', 'haul-out servis', 3),
  ('winter-storage', 'sr', 'vađenje plovila iz vode', 3),
  ('winter-storage', 'en', 'winter storage', 3),
  ('winter-storage', 'en', 'boat storage', 3),
  ('winter-storage', 'en', 'haul-out', 3),
  ('winter-storage', 'en', 'winterizing', 3),
  ('winter-storage', 'en', 'dry storage', 3),
  ('winter-storage', 'tr', 'kışlama', 3),
  ('winter-storage', 'tr', 'tekne kışlama', 3),
  ('winter-storage', 'tr', 'kuru kışlama', 3),
  ('winter-storage', 'tr', 'karaya çekek', 3),
  ('winter-storage', 'tr', 'haul out', 3),
  ('winter-storage', 'de', 'winterlager', 3),
  ('winter-storage', 'de', 'bootslagerung', 3),
  ('winter-storage', 'de', 'winterstellplatz', 3),
  ('winter-storage', 'de', 'bootskonservierung', 3),
  ('winter-storage', 'de', 'krantermin winterlager', 3),
  ('winter-storage', 'it', 'ricovero invernale', 3),
  ('winter-storage', 'it', 'alaggio invernale', 3),
  ('winter-storage', 'it', 'rimessaggio', 3),
  ('winter-storage', 'it', 'rimessaggio invernale', 3),
  ('winter-storage', 'it', 'stoccaggio barche', 3),
  ('winter-storage', 'ru', 'зимняя стоянка', 3),
  ('winter-storage', 'ru', 'зимнее хранение', 3),
  ('winter-storage', 'ru', 'консервация лодки', 3),
  ('winter-storage', 'ru', 'сухая стоянка', 3),
  ('winter-storage', 'ru', 'зимовка лодки', 3),
  ('winter-storage', 'ar', 'تخزين شتوي', 3),
  ('winter-storage', 'ar', 'تخزين القارب', 3),
  ('winter-storage', 'ar', 'تخزين جاف', 3),
  ('winter-storage', 'ar', 'إخراج القارب من الماء', 3),
  ('winter-storage', 'ar', 'مرفأ شتوي', 3),
  ('winter-storage', 'uk', 'зимова стоянка', 3),
  ('winter-storage', 'uk', 'зимове зберігання', 3),
  ('winter-storage', 'uk', 'консервація човна', 3),
  ('winter-storage', 'uk', 'суха стоянка', 3),
  ('winter-storage', 'uk', 'зимівля човна', 3);


-- ----------------------------------------------------------------------------
-- 6. charter-cleaning
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('charter-cleaning', 'me', 'čišćenje čartera', 3),
  ('charter-cleaning', 'me', 'turn-around čišćenje', 3),
  ('charter-cleaning', 'me', 'predaja čartera', 3),
  ('charter-cleaning', 'me', 'čišćenje kabina', 3),
  ('charter-cleaning', 'me', 'pranje veša jahta', 3),
  ('charter-cleaning', 'sr', 'čišćenje čartera', 3),
  ('charter-cleaning', 'sr', 'turn-around čišćenje', 3),
  ('charter-cleaning', 'sr', 'predaja čartera', 3),
  ('charter-cleaning', 'sr', 'čišćenje kabina', 3),
  ('charter-cleaning', 'sr', 'pranje veša jahta', 3),
  ('charter-cleaning', 'en', 'charter cleaning', 3),
  ('charter-cleaning', 'en', 'turnaround cleaning', 3),
  ('charter-cleaning', 'en', 'yacht turn-over', 3),
  ('charter-cleaning', 'en', 'charter handover', 3),
  ('charter-cleaning', 'en', 'yacht laundry', 3),
  ('charter-cleaning', 'tr', 'charter temizliği', 3),
  ('charter-cleaning', 'tr', 'charter teslim temizliği', 3),
  ('charter-cleaning', 'tr', 'yat teslim temizliği', 3),
  ('charter-cleaning', 'tr', 'yat çamaşırı', 3),
  ('charter-cleaning', 'tr', 'kabin temizliği', 3),
  ('charter-cleaning', 'de', 'charterreinigung', 3),
  ('charter-cleaning', 'de', 'yacht-übergabe', 3),
  ('charter-cleaning', 'de', 'turn-around-reinigung', 3),
  ('charter-cleaning', 'de', 'yachtwäscherei', 3),
  ('charter-cleaning', 'de', 'kabinenreinigung', 3),
  ('charter-cleaning', 'it', 'pulizia charter', 3),
  ('charter-cleaning', 'it', 'consegna charter', 3),
  ('charter-cleaning', 'it', 'turn-around yacht', 3),
  ('charter-cleaning', 'it', 'pulizia cabine', 3),
  ('charter-cleaning', 'it', 'lavanderia yacht', 3),
  ('charter-cleaning', 'ru', 'уборка чартера', 3),
  ('charter-cleaning', 'ru', 'передача чартера', 3),
  ('charter-cleaning', 'ru', 'уборка яхты турновер', 3),
  ('charter-cleaning', 'ru', 'стирка для яхты', 3),
  ('charter-cleaning', 'ru', 'уборка кают', 3),
  ('charter-cleaning', 'ar', 'تنظيف بعد التشارتر', 3),
  ('charter-cleaning', 'ar', 'تنظيف بين الرحلات', 3),
  ('charter-cleaning', 'ar', 'تسليم اليخت', 3),
  ('charter-cleaning', 'ar', 'غسيل لليخت', 3),
  ('charter-cleaning', 'ar', 'تنظيف الكبائن', 3),
  ('charter-cleaning', 'uk', 'прибирання чартеру', 3),
  ('charter-cleaning', 'uk', 'прибирання яхти турновер', 3),
  ('charter-cleaning', 'uk', 'передача чартеру', 3),
  ('charter-cleaning', 'uk', 'прання для яхти', 3),
  ('charter-cleaning', 'uk', 'прибирання кают', 3);


-- ----------------------------------------------------------------------------
-- 7. electrical-electronics (marine GPS, AIS, chartplotter, VHF)
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('electrical-electronics', 'me', 'elektrika plovila', 3),
  ('electrical-electronics', 'me', 'gps plovila', 3),
  ('electrical-electronics', 'me', 'ais plovila', 3),
  ('electrical-electronics', 'me', 'chartplotter', 3),
  ('electrical-electronics', 'me', 'vhf radio', 3),
  ('electrical-electronics', 'sr', 'elektrika plovila', 3),
  ('electrical-electronics', 'sr', 'gps plovila', 3),
  ('electrical-electronics', 'sr', 'ais plovila', 3),
  ('electrical-electronics', 'sr', 'chartplotter', 3),
  ('electrical-electronics', 'sr', 'vhf radio', 3),
  ('electrical-electronics', 'en', 'marine electronics', 3),
  ('electrical-electronics', 'en', 'gps boat', 3),
  ('electrical-electronics', 'en', 'ais', 3),
  ('electrical-electronics', 'en', 'chartplotter', 3),
  ('electrical-electronics', 'en', 'vhf radio', 3),
  ('electrical-electronics', 'en', 'marine wiring', 3),
  ('electrical-electronics', 'tr', 'tekne elektroniği', 3),
  ('electrical-electronics', 'tr', 'tekne gps', 3),
  ('electrical-electronics', 'tr', 'ais tekne', 3),
  ('electrical-electronics', 'tr', 'chartplotter tekne', 3),
  ('electrical-electronics', 'tr', 'vhf telsiz', 3),
  ('electrical-electronics', 'tr', 'tekne elektriği', 3),
  ('electrical-electronics', 'de', 'bootselektronik', 3),
  ('electrical-electronics', 'de', 'gps boot', 3),
  ('electrical-electronics', 'de', 'ais boot', 3),
  ('electrical-electronics', 'de', 'kartenplotter', 3),
  ('electrical-electronics', 'de', 'ukw funk', 3),
  ('electrical-electronics', 'de', 'bootselektrik', 3),
  ('electrical-electronics', 'it', 'elettronica nautica', 3),
  ('electrical-electronics', 'it', 'gps barca', 3),
  ('electrical-electronics', 'it', 'ais barca', 3),
  ('electrical-electronics', 'it', 'chartplotter barca', 3),
  ('electrical-electronics', 'it', 'vhf nautico', 3),
  ('electrical-electronics', 'it', 'impianto elettrico barca', 3),
  ('electrical-electronics', 'ru', 'лодочная электроника', 3),
  ('electrical-electronics', 'ru', 'gps лодка', 3),
  ('electrical-electronics', 'ru', 'ais лодка', 3),
  ('electrical-electronics', 'ru', 'картплоттер', 3),
  ('electrical-electronics', 'ru', 'укв радио', 3),
  ('electrical-electronics', 'ru', 'судовая электрика', 3),
  ('electrical-electronics', 'ar', 'إلكترونيات بحرية', 3),
  ('electrical-electronics', 'ar', 'جي بي إس قارب', 3),
  ('electrical-electronics', 'ar', 'شارت بلوتر', 3),
  ('electrical-electronics', 'ar', 'راديو بحري', 3),
  ('electrical-electronics', 'ar', 'كهرباء قارب', 3),
  ('electrical-electronics', 'uk', 'судова електроніка', 3),
  ('electrical-electronics', 'uk', 'gps човен', 3),
  ('electrical-electronics', 'uk', 'ais човен', 3),
  ('electrical-electronics', 'uk', 'картплотер', 3),
  ('electrical-electronics', 'uk', 'укв радіо', 3),
  ('electrical-electronics', 'uk', 'судова електрика', 3);


-- ----------------------------------------------------------------------------
-- 8. sail-canvas
-- ----------------------------------------------------------------------------

INSERT INTO public.glatko_search_synonyms (canonical_slug, locale, synonym, weight) VALUES
  ('sail-canvas', 'me', 'jedra', 3),
  ('sail-canvas', 'me', 'jedrar', 3),
  ('sail-canvas', 'me', 'popravka jedara', 3),
  ('sail-canvas', 'me', 'bimini', 3),
  ('sail-canvas', 'me', 'tenda jahta', 3),
  ('sail-canvas', 'sr', 'jedra', 3),
  ('sail-canvas', 'sr', 'jedrar', 3),
  ('sail-canvas', 'sr', 'popravka jedara', 3),
  ('sail-canvas', 'sr', 'bimini', 3),
  ('sail-canvas', 'sr', 'tenda jahta', 3),
  ('sail-canvas', 'en', 'sailmaker', 3),
  ('sail-canvas', 'en', 'sail repair', 3),
  ('sail-canvas', 'en', 'bimini', 3),
  ('sail-canvas', 'en', 'yacht canvas', 3),
  ('sail-canvas', 'en', 'dodger', 3),
  ('sail-canvas', 'en', 'spinnaker', 3),
  ('sail-canvas', 'tr', 'yelken', 3),
  ('sail-canvas', 'tr', 'yelken tamiri', 3),
  ('sail-canvas', 'tr', 'yat brandası', 3),
  ('sail-canvas', 'tr', 'bimini', 3),
  ('sail-canvas', 'tr', 'güneşlik branda', 3),
  ('sail-canvas', 'tr', 'spinaker', 3),
  ('sail-canvas', 'de', 'segelmacher', 3),
  ('sail-canvas', 'de', 'segelreparatur', 3),
  ('sail-canvas', 'de', 'bimini', 3),
  ('sail-canvas', 'de', 'bootsplane', 3),
  ('sail-canvas', 'de', 'spinnaker', 3),
  ('sail-canvas', 'de', 'segeltuch', 3),
  ('sail-canvas', 'it', 'velaio', 3),
  ('sail-canvas', 'it', 'riparazione vele', 3),
  ('sail-canvas', 'it', 'bimini', 3),
  ('sail-canvas', 'it', 'tendalini', 3),
  ('sail-canvas', 'it', 'spinnaker', 3),
  ('sail-canvas', 'it', 'tela nautica', 3),
  ('sail-canvas', 'ru', 'мастер парусов', 3),
  ('sail-canvas', 'ru', 'ремонт парусов', 3),
  ('sail-canvas', 'ru', 'бимини', 3),
  ('sail-canvas', 'ru', 'тент яхта', 3),
  ('sail-canvas', 'ru', 'спинакер', 3),
  ('sail-canvas', 'ru', 'парусина', 3),
  ('sail-canvas', 'ar', 'صانع أشرعة', 3),
  ('sail-canvas', 'ar', 'إصلاح الأشرعة', 3),
  ('sail-canvas', 'ar', 'بيميني', 3),
  ('sail-canvas', 'ar', 'مظلة يخت', 3),
  ('sail-canvas', 'ar', 'شراع سبينكر', 3),
  ('sail-canvas', 'ar', 'قماش بحري', 3),
  ('sail-canvas', 'uk', 'майстер вітрил', 3),
  ('sail-canvas', 'uk', 'ремонт вітрил', 3),
  ('sail-canvas', 'uk', 'бімінь', 3),
  ('sail-canvas', 'uk', 'тент яхта', 3),
  ('sail-canvas', 'uk', 'спинакер', 3),
  ('sail-canvas', 'uk', 'вітрило', 3);

COMMIT;
